[package]
name = "Orderbook"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
anyhow = "1.0.100"
bcrypt = "0.17.1"
chrono = "0.4.42"
jsonwebtoken = "10.2.0"
serde = "1.0.228"
thiserror = "2.0.17"
tokio = "1.48.0"
uuid = "1.18.1"
